offline_twitch_global_emotes_list = [{'code': 'FutureMan', 'id': 98562},
                                     {'code': 'DAESuppy', 'id': 973},
                                     {'code': 'PartyHat', 'id': 965738},
                                     {'code': 'EarthDay', 'id': 959018},
                                     {'code': 'PMSTwin', 'id': 92},
                                     {'code': 'ChefFrank', 'id': 90129},
                                     {'code': 'StinkyCheese', 'id': 90076},
                                     {'code': 'NomNom', 'id': 90075},
                                     {'code': 'SmoocherZ', 'id': 89945}, {'code': 'PogChamp', 'id': 88},
                                     {'code': 'ShazBotstix', 'id': 87}, {'code': 'TombRaid', 'id': 864205},
                                     {'code': 'BibleThump', 'id': 86}, {'code': 'cmonBruh', 'id': 84608},
                                     {'code': 'KappaWealth', 'id': 81997}, {'code': 'MikeHogu', 'id': 81636},
                                     {'code': 'VoHiYo', 'id': 81274}, {'code': 'KomodoHype', 'id': 81273},
                                     {'code': 'SeriousSloth', 'id': 81249}, {'code': 'OSFrog', 'id': 81248},
                                     {'code': 'OhMyDog', 'id': 81103}, {'code': 'KappaClaus', 'id': 74510},
                                     {'code': 'TheThing', 'id': 7427}, {'code': 'AsianGlow', 'id': 74},
                                     {'code': 'DBstyle', 'id': 73}, {'code': 'PopCorn', 'id': 724216},
                                     {'code': 'KappaRoss', 'id': 70433}, {'code': 'BloodTrail', 'id': 69},
                                     {'code': 'MingLee', 'id': 68856}, {'code': 'HassanChop', 'id': 68},
                                     {'code': 'OneHand', 'id': 66}, {'code': 'FrankerZ', 'id': 65},
                                     {'code': 'SeemsGood', 'id': 64138}, {'code': 'twitchRaid', 'id': 62836},
                                     {'code': 'bleedPurple', 'id': 62835}, {'code': 'duDudu', 'id': 62834},
                                     {'code': 'riPepperonis', 'id': 62833}, {'code': 'FBtouchdown', 'id': 626795},
                                     {'code': 'PurpleStar', 'id': 624501}, {'code': 'NotLikeThis', 'id': 58765},
                                     {'code': 'DendiFace', 'id': 58135}, {'code': 'CoolCat', 'id': 58127},
                                     {'code': 'KappaPride', 'id': 55338}, {'code': 'GreenTeam', 'id': 530890},
                                     {'code': 'RedTeam', 'id': 530888}, {'code': 'ShadyLulu', 'id': 52492},
                                     {'code': 'SMOrc', 'id': 52}, {'code': 'ArgieB8', 'id': 51838},
                                     {'code': 'TPFufun', 'id': 508650}, {'code': 'ArsonNoSexy', 'id': 50},
                                     {'code': 'CorgiDerp', 'id': 49106}, {'code': 'TwitchVotes', 'id': 479745},
                                     {'code': 'PunchTrees', 'id': 47}, {'code': 'HumbleLife', 'id': 46881},
                                     {'code': 'DarkMode', 'id': 461298}, {'code': 'SSSsss', 'id': 46},
                                     {'code': 'HSWP', 'id': 446979}, {'code': 'HSCheers', 'id': 444572},
                                     {'code': 'EleGiggle', 'id': 4339}, {'code': 'RitzMitz', 'id': 4338},
                                     {'code': 'YouWHY', 'id': 4337}, {'code': 'PowerUpL', 'id': 425688},
                                     {'code': 'PowerUpR', 'id': 425671}, {'code': 'LUL', 'id': 425618},
                                     {'code': 'PipeHype', 'id': 4240}, {'code': 'Kreygasm', 'id': 41},
                                     {'code': 'BrokeBack', 'id': 4057}, {'code': 'KevinTurtle', 'id': 40},
                                     {'code': 'PraiseIt', 'id': 38586}, {'code': 'TTours', 'id': 38436},
                                     {'code': 'ANELE', 'id': 3792}, {'code': 'EntropyWins', 'id': 376765},
                                     {'code': 'PanicVis', 'id': 3668}, {'code': 'GrammarKing', 'id': 3632},
                                     {'code': 'FailFish', 'id': 360}, {'code': 'PJSalt', 'id': 36},
                                     {'code': 'HotPokket', 'id': 357}, {'code': '4Head', 'id': 354},
                                     {'code': 'mcaT', 'id': 35063}, {'code': 'NotATK', 'id': 34875},
                                     {'code': 'PeoplesChamp', 'id': 3412}, {'code': 'SwiftRage', 'id': 34},
                                     {'code': 'DansGame', 'id': 33}, {'code': 'TPcrunchyroll', 'id': 323914},
                                     {'code': 'GingerPower', 'id': 32}, {'code': 'HeyGuys', 'id': 30259},
                                     {'code': 'VirtualHug', 'id': 301696583}, {'code': 'BOP', 'id': 301428702},
                                     {'code': 'Mau5', 'id': 30134}, {'code': 'PorscheWIN', 'id': 300745158},
                                     {'code': 'SingsNote', 'id': 300116350}, {'code': 'SingsMic', 'id': 300116349},
                                     {'code': 'TwitchSings', 'id': 300116344}, {'code': 'BCWarrior', 'id': 30},
                                     {'code': 'PRChase', 'id': 28328}, {'code': 'WutFace', 'id': 28087},
                                     {'code': 'MrDestructoid', 'id': 28}, {'code': 'BuddhaBar', 'id': 27602},
                                     {'code': 'PermaSmug', 'id': 27509}, {'code': 'JonCarnage', 'id': 26},
                                     {'code': 'Kappa', 'id': 25}, {'code': 'ResidentSleeper', 'id': 245},
                                     {'code': 'FUNgineer', 'id': 244}, {'code': 'panicBasket', 'id': 22998},
                                     {'code': 'BabyRage', 'id': 22639}, {'code': 'RedCoat', 'id': 22},
                                     {'code': 'SoonerLater', 'id': 2113050}, {'code': 'HassaanChop', 'id': 20225},
                                     {'code': 'TwitchUnity', 'id': 196892}, {'code': 'Squid4', 'id': 191767},
                                     {'code': 'Squid3', 'id': 191764}, {'code': 'Squid2', 'id': 191763},
                                     {'code': 'Squid1', 'id': 191762}, {'code': 'CrreamAwk', 'id': 191313},
                                     {'code': 'SoBayed', 'id': 1906}, {'code': 'BigBrother', 'id': 1904},
                                     {'code': 'Keepo', 'id': 1902}, {'code': 'Kippa', 'id': 1901},
                                     {'code': 'RalpherZ', 'id': 1900}, {'code': 'TF2John', 'id': 1899},
                                     {'code': 'ThunBeast', 'id': 1898}, {'code': 'WholeWheat', 'id': 1896},
                                     {'code': 'TheRinger', 'id': 18}, {'code': 'HolidayTree', 'id': 1713825},
                                     {'code': 'HolidaySanta', 'id': 1713822}, {'code': 'HolidayPresent', 'id': 1713819},
                                     {'code': 'HolidayOrnament', 'id': 1713818}, {'code': 'HolidayLog', 'id': 1713816},
                                     {'code': 'HolidayCookie', 'id': 1713813}, {'code': 'StoneLightning', 'id': 17},
                                     {'code': 'CarlSmile', 'id': 166266}, {'code': 'TwitchLit', 'id': 166263},
                                     {'code': 'TehePelo', 'id': 160404}, {'code': 'TearGlove', 'id': 160403},
                                     {'code': 'SabaPing', 'id': 160402}, {'code': 'PunOko', 'id': 160401},
                                     {'code': 'KonCha', 'id': 160400}, {'code': 'Kappu', 'id': 160397},
                                     {'code': 'InuyoFace', 'id': 160396}, {'code': 'BigPhish', 'id': 160395},
                                     {'code': 'BegWan', 'id': 160394}, {'code': 'ThankEgg', 'id': 160392},
                                     {'code': 'OptimizePrime', 'id': 16}, {'code': 'GunRun', 'id': 1584743},
                                     {'code': 'MorphinTime', 'id': 156787}, {'code': 'PixelBob', 'id': 1547903},
                                     {'code': 'BlessRNG', 'id': 153556}, {'code': 'JKanStyle', 'id': 15},
                                     {'code': 'TheIlluminati', 'id': 145315}, {'code': 'FBPenalty', 'id': 1441289},
                                     {'code': 'FBChallenge', 'id': 1441285}, {'code': 'FBCatch', 'id': 1441281},
                                     {'code': 'FBBlock', 'id': 1441276}, {'code': 'FBSpiral', 'id': 1441273},
                                     {'code': 'FBPass', 'id': 1441271}, {'code': 'FBRun', 'id': 1441261},
                                     {'code': 'TBAngel', 'id': 143490}, {'code': 'MVGame', 'id': 142140},
                                     {'code': 'NinjaGrumpy', 'id': 138325}, {'code': 'PartyTime', 'id': 135393},
                                     {'code': 'RlyTho', 'id': 134256}, {'code': 'UWot', 'id': 134255},
                                     {'code': 'YouDontSay', 'id': 134254}, {'code': 'KAPOW', 'id': 133537},
                                     {'code': 'ItsBoshyTime', 'id': 133468},
                                     {'code': 'GenderFluidPride', 'id': 1297281},
                                     {'code': 'NonBinaryPride', 'id': 1297279}, {'code': 'MaxLOL', 'id': 1290325},
                                     {'code': 'CoolStoryBob', 'id': 123171}, {'code': 'IntersexPride', 'id': 1221184},
                                     {'code': 'TwitchRPG', 'id': 1220086}, {'code': 'TriHard', 'id': 120232},
                                     {'code': 'SuperVinlin', 'id': 118772}, {'code': 'FreakinStinkin', 'id': 117701},
                                     {'code': 'Poooound', 'id': 117484}, {'code': 'CurseLit', 'id': 116625},
                                     {'code': 'BatChest', 'id': 115234}, {'code': 'BrainSlug', 'id': 115233},
                                     {'code': 'PrimeMe', 'id': 115075}, {'code': 'StrawBeary', 'id': 114876},
                                     {'code': 'RaccAttack', 'id': 114870}, {'code': 'UncleNox', 'id': 114856},
                                     {'code': 'WTRuck', 'id': 114847}, {'code': 'TooSpicy', 'id': 114846},
                                     {'code': 'Jebaited', 'id': 114836}, {'code': 'DogFace', 'id': 114835},
                                     {'code': 'BlargNaut', 'id': 114738}, {'code': 'PansexualPride', 'id': 1130349},
                                     {'code': 'AsexualPride', 'id': 1130348}, {'code': 'TakeNRG', 'id': 112292},
                                     {'code': 'GivePLZ', 'id': 112291}, {'code': 'imGlitch', 'id': 112290},
                                     {'code': 'pastaThat', 'id': 112289}, {'code': 'copyThis', 'id': 112288},
                                     {'code': 'UnSane', 'id': 111792}, {'code': 'DatSheffy', 'id': 111700},
                                     {'code': 'TheTarFu', 'id': 111351}, {'code': 'PicoMause', 'id': 111300},
                                     {'code': 'TinyFace', 'id': 111119}, {'code': 'DrinkPurple', 'id': 110785},
                                     {'code': 'DxCat', 'id': 110734}, {'code': 'RuleFive', 'id': 107030},
                                     {'code': 'TransgenderPride', 'id': 1064995}, {'code': 'GayPride', 'id': 1064991},
                                     {'code': 'LesbianPride', 'id': 1064988}, {'code': 'BisexualPride', 'id': 1064987},
                                     {'code': 'VoteNay', 'id': 106294}, {'code': 'VoteYea', 'id': 106293},
                                     {'code': 'PJSugar', 'id': 102556}, {'code': 'DoritosChip', 'id': 102242},
                                     {'code': 'OpieOP', 'id': 100590}, {'code': 'PinkMercy', 'id': 1003190},
                                     {'code': 'MercyWing2', 'id': 1003189}, {'code': 'MercyWing1', 'id': 1003187}]

nouns_list = ['word', 'people', 'history', 'way', 'art', 'world', 'information', 'map', 'two', 'family', 'government',
              'health', 'system', 'computer', 'meat', 'year', 'thanks', 'music', 'person', 'reading', 'method', 'data',
              'food', 'understanding', 'law', 'bird', 'literature', 'problem', 'software', 'control',
              'knowledge', 'power', 'ability', 'love', 'internet', 'television', 'science', 'library',
              'nature', 'fact', 'product', 'idea', 'temperature', 'investment', 'area', 'society', 'activity', 'story',
              'industry', 'media', 'thing', 'oven', 'community', 'definition', 'safety', 'quality', 'development',
              'language', 'management', 'player', 'variety', 'video', 'week', 'security', 'country', 'exam', 'movie',
              'organization', 'equipment', 'physics', 'analysis', 'thought', 'basis', 'boyfriend',
              'direction', 'strategy', 'technology', 'army', 'camera', 'freedom', 'paper', 'environment', 'child',
              'month', 'marketing', 'university', 'writing', 'article', 'department', 'difference',
              'goal', 'news', 'audience', 'fishing', 'growth', 'income', 'marriage', 'user', 'combination', 'failure',
              'meaning', 'medicine', 'philosophy', 'teacher', 'communication', 'night', 'chemistry', 'disease', 'disk',
              'energy', 'nation', 'road', 'role', 'soup', 'advertising', 'location', 'success', 'addition', 'apartment',
              'education', 'math', 'moment', 'painting', 'politics', 'attention', 'decision', 'event', 'property',
              'shopping', 'student', 'wood', 'competition', 'distribution', 'entertainment', 'office', 'population',
              'president', 'unit', 'category', 'cigarette', 'context', 'introduction', 'opportunity', 'performance',
              'driver', 'flight', 'length', 'magazine', 'newspaper', 'relationship', 'teaching', 'cell', 'dealer',
              'finding', 'lake', 'member', 'message', 'phone', 'scene', 'appearance', 'association', 'concept',
              'customer', 'death', 'discussion', 'housing', 'inflation', 'insurance', 'mood', 'woman', 'advice',
              'blood', 'effort', 'expression', 'importance', 'opinion', 'payment', 'reality', 'responsibility',
              'situation', 'skill', 'statement', 'wealth', 'application', 'city', 'county', 'depth', 'estate',
              'foundation', 'grandmother', 'heart', 'perspective', 'photo', 'recipe', 'studio', 'topic', 'collection',
              'depression', 'imagination', 'passion', 'percentage', 'resource', 'setting', 'ad', 'agency', 'college',
              'connection', 'criticism', 'debt', 'description', 'memory', 'patience', 'secretary', 'solution',
              'administration', 'aspect', 'attitude', 'director', 'personality', 'psychology', 'recommendation',
              'response', 'selection', 'storage', 'version', 'alcohol', 'argument', 'complaint', 'contract', 'emphasis',
              'highway', 'loss', 'membership', 'possession', 'preparation', 'steak', 'union', 'agreement', 'cancer',
              'currency', 'employment', 'engineering', 'entry', 'interaction', 'mixture', 'preference', 'region',
              'republic', 'tradition', 'virus', 'actor', 'classroom', 'delivery', 'device', 'difficulty', 'drama',
              'election', 'engine', 'football', 'guidance', 'hotel', 'owner', 'priority', 'protection', 'suggestion',
              'tension', 'variation', 'anxiety', 'atmosphere', 'awareness', 'bath', 'bread', 'candidate', 'climate',
              'comparison', 'confusion', 'construction', 'elevator', 'emotion', 'employee', 'employer', 'guest',
              'height', 'leadership', 'mall', 'manager', 'operation', 'recording', 'sample', 'transportation',
              'charity', 'cousin', 'disaster', 'editor', 'efficiency', 'excitement', 'extent', 'feedback', 'guitar',
              'homework', 'leader', 'mom', 'outcome', 'permission', 'presentation', 'promotion', 'reflection',
              'refrigerator', 'resolution', 'revenue', 'session', 'singer', 'tennis', 'basket', 'bonus', 'cabinet',
              'childhood', 'church', 'clothes', 'coffee', 'dinner', 'drawing', 'hair', 'hearing', 'initiative',
              'judgment', 'lab', 'measurement', 'mode', 'mud', 'orange', 'poetry', 'police', 'possibility', 'procedure',
              'queen', 'ratio', 'relation', 'restaurant', 'satisfaction', 'sector', 'signature', 'significance', 'song',
              'tooth', 'town', 'vehicle', 'volume', 'wife', 'accident', 'airport', 'appointment', 'arrival',
              'assumption', 'baseball', 'chapter', 'committee', 'conversation', 'database', 'enthusiasm', 'error',
              'explanation', 'farmer', 'gate', 'girl', 'hall', 'historian', 'hospital', 'injury', 'instruction',
              'maintenance', 'manufacturer', 'meal', 'perception', 'pie', 'poem', 'presence', 'proposal', 'reception',
              'replacement', 'revolution', 'river', 'son', 'speech', 'tea', 'village', 'warning', 'winner', 'worker',
              'writer', 'assistance', 'breath', 'buyer', 'chest', 'chocolate', 'conclusion', 'contribution', 'cookie',
              'courage', 'dad', 'desk', 'drawer', 'establishment', 'examination', 'garbage', 'grocery', 'honey',
              'impression', 'improvement', 'independence', 'insect', 'inspection', 'inspector', 'king', 'ladder',
              'menu', 'penalty', 'piano', 'potato', 'profession', 'professor', 'quantity', 'reaction', 'requirement',
              'salad', 'sister', 'supermarket', 'tongue', 'weakness', 'wedding', 'affair', 'ambition', 'analyst',
              'apple', 'assignment', 'assistant', 'bathroom', 'bedroom', 'beer', 'birthday', 'celebration',
              'championship', 'cheek', 'client', 'consequence', 'departure', 'diamond', 'dirt', 'ear', 'fortune',
              'friendship', 'funeral', 'gene', 'girlfriend', 'hat', 'indication', 'intention', 'lady', 'midnight',
              'negotiation', 'obligation', 'passenger', 'pizza', 'platform', 'poet', 'pollution', 'recognition',
              'reputation', 'shirt', 'sir', 'speaker', 'stranger', 'surgery', 'sympathy', 'tale', 'throat', 'trainer',
              'uncle', 'youth', 'time', 'work', 'film', 'water', 'money', 'example', 'while', 'business', 'study',
              'game', 'life', 'form', 'air', 'day', 'place', 'number', 'part', 'field', 'fish', 'back', 'process',
              'heat', 'hand', 'experience', 'job', 'book', 'end', 'point', 'type', 'home', 'economy', 'value', 'body',
              'market', 'guide', 'interest', 'state', 'radio', 'course', 'company', 'price', 'size', 'card', 'list',
              'mind', 'trade', 'line', 'care', 'group', 'risk', 'word', 'fat', 'force', 'key', 'light', 'training',
              'name', 'school', 'top', 'amount', 'level', 'order', 'practice', 'research', 'sense', 'service', 'piece',
              'web', 'boss', 'sport', 'fun', 'house', 'page', 'term', 'test', 'answer', 'sound', 'focus', 'matter',
              'kind', 'soil', 'board', 'oil', 'picture', 'access', 'garden', 'range', 'rate', 'reason', 'future',
              'site', 'demand', 'exercise', 'image', 'case', 'cause', 'coast', 'action', 'age', 'bad', 'boat', 'record',
              'result', 'section', 'building', 'mouse', 'cash', 'class', 'nothing', 'period', 'plan', 'store', 'tax',
              'side', 'subject', 'space', 'rule', 'stock', 'weather', 'chance', 'figure', 'man', 'model', 'source',
              'beginning', 'earth', 'program', 'chicken', 'design', 'feature', 'head', 'material', 'purpose',
              'question', 'rock', 'salt', 'act', 'birth', 'car', 'dog', 'object', 'scale', 'sun', 'note', 'profit',
              'rent', 'speed', 'style', 'war', 'bank', 'craft', 'half', 'inside', 'outside', 'standard', 'bus',
              'exchange', 'eye', 'fire', 'position', 'pressure', 'stress', 'advantage', 'benefit', 'box', 'frame',
              'issue', 'step', 'cycle', 'face', 'item', 'metal', 'paint', 'review', 'room', 'screen', 'structure',
              'view', 'account', 'ball', 'discipline', 'medium', 'share', 'balance', 'bit', 'black', 'bottom', 'choice',
              'gift', 'impact', 'machine', 'shape', 'tool', 'wind', 'address', 'average', 'career', 'culture',
              'morning', 'pot', 'sign', 'table', 'task', 'condition', 'contact', 'credit', 'egg', 'hope', 'ice',
              'network', 'north', 'square', 'attempt', 'date', 'effect', 'link', 'post', 'star', 'voice', 'capital',
              'challenge', 'friend', 'self', 'shot', 'brush', 'couple', 'debate', 'exit', 'front', 'function', 'lack',
              'living', 'plant', 'plastic', 'spot', 'summer', 'taste', 'theme', 'track', 'wing', 'brain', 'button',
              'click', 'desire', 'foot', 'gas', 'influence', 'notice', 'rain', 'wall', 'base', 'damage', 'distance',
              'feeling', 'pair', 'savings', 'staff', 'sugar', 'target', 'text', 'animal', 'author', 'budget',
              'discount', 'file', 'ground', 'lesson', 'minute', 'officer', 'phase', 'reference', 'register', 'sky',
              'stage', 'stick', 'title', 'trouble', 'bowl', 'bridge', 'campaign', 'character', 'club', 'edge',
              'evidence', 'fan', 'letter', 'lock', 'maximum', 'novel', 'option', 'pack', 'park', 'plenty', 'quarter',
              'skin', 'sort', 'weight', 'baby', 'background', 'carry', 'dish', 'factor', 'fruit', 'glass', 'joint',
              'master', 'muscle', 'red', 'strength', 'traffic', 'trip', 'vegetable', 'appeal', 'chart', 'gear', 'ideal',
              'kitchen', 'land', 'log', 'mother', 'net', 'party', 'principle', 'relative', 'sale', 'season', 'signal',
              'spirit', 'street', 'tree', 'wave', 'belt', 'bench', 'commission', 'copy', 'drop', 'minimum', 'path',
              'progress', 'project', 'sea', 'south', 'status', 'stuff', 'ticket', 'tour', 'angle', 'blue', 'breakfast',
              'confidence', 'daughter', 'degree', 'doctor', 'dot', 'dream', 'duty', 'essay', 'father', 'fee', 'finance',
              'hour', 'juice', 'limit', 'luck', 'milk', 'mouth', 'peace', 'pipe', 'seat', 'stable', 'storm',
              'substance', 'team', 'trick', 'afternoon', 'bat', 'beach', 'blank', 'catch', 'chain', 'consideration',
              'cream', 'crew', 'detail', 'gold', 'interview', 'kid', 'mark', 'match', 'mission', 'pain', 'pleasure',
              'score', 'screw', 'sex', 'shop', 'shower', 'suit', 'tone', 'window', 'agent', 'band', 'block', 'bone',
              'calendar', 'cap', 'coat', 'contest', 'corner', 'court', 'cup', 'district', 'door', 'east', 'finger',
              'garage', 'guarantee', 'hole', 'hook', 'implement', 'layer', 'lecture', 'lie', 'manner', 'meeting',
              'nose', 'parking', 'partner', 'profile', 'respect', 'rice', 'routine', 'schedule', 'swimming',
              'telephone', 'tip', 'winter', 'airline', 'bag', 'battle', 'bed', 'bill', 'bother', 'cake', 'code',
              'curve', 'designer', 'dimension', 'dress', 'ease', 'emergency', 'evening', 'extension', 'farm', 'fight',
              'gap', 'grade', 'holiday', 'horror', 'horse', 'host', 'husband', 'loan', 'mistake', 'mountain', 'nail',
              'noise', 'occasion', 'package', 'patient', 'pause', 'phrase', 'proof', 'race', 'relief', 'sand',
              'sentence', 'shoulder', 'smoke', 'stomach', 'string', 'tourist', 'towel', 'vacation', 'west', 'wheel',
              'wine', 'arm', 'aside', 'associate', 'bet', 'blow', 'border', 'branch', 'breast', 'brother', 'buddy',
              'bunch', 'chip', 'coach', 'cross', 'document', 'draft', 'dust', 'expert', 'floor', 'god', 'golf', 'habit',
              'iron', 'judge', 'knife', 'landscape', 'league', 'mail', 'mess', 'native', 'opening', 'parent', 'pattern',
              'pin', 'pool', 'pound', 'request', 'salary', 'shame', 'shelter', 'shoe', 'silver', 'tackle', 'tank',
              'trust', 'assist', 'bake', 'bar', 'bell', 'bike', 'blame', 'boy', 'brick', 'chair', 'closet', 'clue',
              'collar', 'comment', 'conference', 'devil', 'diet', 'fear', 'fuel', 'glove', 'jacket', 'lunch', 'monitor',
              'mortgage', 'nurse', 'pace', 'panic', 'peak', 'plane', 'reward', 'row', 'sandwich', 'shock', 'spite',
              'spray', 'surprise', 'till', 'transition', 'weekend', 'welcome', 'yard', 'alarm', 'bend', 'bicycle',
              'bite', 'blind', 'bottle', 'cable', 'candle', 'clerk', 'cloud', 'concert', 'counter', 'flower',
              'grandfather', 'harm', 'knee', 'lawyer', 'leather', 'load', 'mirror', 'neck', 'pension', 'plate',
              'purple', 'ruin', 'ship', 'skirt', 'slice', 'snow', 'specialist', 'stroke', 'switch', 'trash', 'tune',
              'zone', 'anger', 'award', 'bid', 'bitter', 'boot', 'bug', 'camp', 'candy', 'carpet', 'cat', 'champion',
              'channel', 'clock', 'comfort', 'cow', 'crack', 'engineer', 'entrance', 'fault', 'grass', 'guy', 'hell',
              'highlight', 'incident', 'island', 'joke', 'jury', 'leg', 'lip', 'mate', 'motor', 'nerve', 'passage',
              'pen', 'pride', 'priest', 'prize', 'promise', 'resident', 'resort', 'ring', 'roof', 'rope', 'sail',
              'scheme', 'script', 'sock', 'station', 'toe', 'tower', 'truck', 'witness', 'a', 'you', 'it', 'can',
              'will', 'if', 'one', 'many', 'most', 'other', 'use', 'make', 'good', 'look', 'help', 'go', 'great',
              'being', 'few', 'might', 'still', 'public', 'read', 'keep', 'start', 'give', 'human', 'local', 'general',
              'she', 'specific', 'long', 'play', 'feel', 'high', 'tonight', 'put', 'common', 'set', 'change', 'simple',
              'past', 'big', 'possible', 'particular', 'today', 'major', 'personal', 'current', 'national', 'cut',
              'natural', 'physical', 'show', 'try', 'check', 'second', 'call', 'move', 'pay', 'let', 'increase',
              'single', 'individual', 'turn', 'ask', 'buy', 'guard', 'hold', 'main', 'offer', 'potential',
              'professional', 'international', 'travel', 'cook', 'alternative', 'following', 'special', 'working',
              'whole', 'dance', 'excuse', 'cold', 'commercial', 'low', 'purchase', 'deal', 'primary', 'worth', 'fall',
              'necessary', 'positive', 'produce', 'search', 'present', 'spend', 'talk', 'creative', 'tell', 'cost',
              'drive', 'green', 'support', 'glad', 'remove', 'return', 'run', 'complex', 'due', 'effective', 'middle',
              'regular', 'reserve', 'independent', 'leave', 'original', 'reach', 'rest', 'serve', 'watch', 'beautiful',
              'charge', 'active', 'break', 'negative', 'safe', 'stay', 'visit', 'visual', 'affect', 'cover', 'report',
              'rise', 'walk', 'white', 'beyond', 'junior', 'pick', 'unique', 'anything', 'classic', 'final', 'lift',
              'mix', 'private', 'stop', 'teach', 'western', 'concern', 'familiar', 'fly', 'official', 'broad',
              'comfortable', 'gain', 'maybe', 'rich', 'save', 'stand', 'young', 'fail', 'heavy', 'hello', 'lead',
              'listen', 'valuable', 'worry', 'handle', 'leading', 'meet', 'release', 'sell', 'finish', 'normal',
              'press', 'ride', 'secret', 'spread', 'spring', 'tough', 'wait', 'brown', 'deep', 'display', 'flow', 'hit',
              'objective', 'shoot', 'touch', 'cancel', 'chemical', 'cry', 'dump', 'extreme', 'push', 'conflict', 'eat',
              'fill', 'formal', 'jump', 'kick', 'opposite', 'pass', 'pitch', 'remote', 'total', 'treat', 'vast',
              'abuse', 'beat', 'burn', 'deposit', 'print', 'raise', 'sleep', 'somewhere', 'advance', 'anywhere',
              'consist', 'dark', 'double', 'draw', 'equal', 'fix', 'hire', 'internal', 'join', 'kill', 'sensitive',
              'tap', 'win', 'attack', 'claim', 'constant', 'drag', 'drink', 'guess', 'minor', 'pull', 'raw', 'soft',
              'solid', 'wear', 'weird', 'wonder', 'annual', 'count', 'dead', 'doubt', 'feed', 'forever', 'impress',
              'nobody', 'repeat', 'round', 'sing', 'slide', 'strip', 'whereas', 'wish', 'combine', 'command', 'dig',
              'divide', 'equivalent', 'hang', 'hunt', 'initial', 'march', 'mention', 'smell', 'spiritual', 'survey',
              'tie', 'adult', 'brief', 'crazy', 'escape', 'gather', 'hate', 'prior', 'repair', 'rough', 'sad',
              'scratch', 'sick', 'strike', 'employ', 'external', 'hurt', 'illegal', 'laugh', 'lay', 'mobile', 'nasty',
              'ordinary', 'respond', 'royal', 'senior', 'split', 'strain', 'struggle', 'swim', 'train', 'upper', 'wash',
              'yellow', 'convert', 'crash', 'dependent', 'fold', 'funny', 'grab', 'hide', 'miss', 'permit', 'quote',
              'recover', 'resolve', 'roll', 'sink', 'slip', 'spare', 'suspect', 'sweet', 'swing', 'twist', 'upstairs',
              'usual', 'abroad', 'brave', 'calm', 'concentrate', 'estimate', 'grand', 'male', 'mine', 'prompt', 'quiet',
              'refuse', 'regret', 'reveal', 'rush', 'shake', 'shift', 'shine', 'steal', 'suck', 'surround', 'anybody',
              'bear', 'brilliant', 'dare', 'dear', 'delay', 'drunk', 'female', 'hurry', 'inevitable', 'invite', 'kiss',
              'neat', 'pop', 'punch', 'quit', 'reply', 'representative', 'resist', 'rip', 'rub', 'silly', 'smile',
              'spell', 'stretch', 'stupid', 'tear', 'temporary', 'tomorrow', 'wake', 'wrap', 'yesterday']
